export default [{
  id: '1',
  name: 'React',
  img: 'http://unsplash.com/photos/PC_lbSSxCZE/download?force=true',
  text: `
Meow sleep on dog bed, force dog to sleep on floor but my slave human didn't give me any food so i pooped on the floor scratch leg; meow for can opener to feed me vommit food and eat it again. Rub face on owner chase red laser dot, for pee in human's bed until he cleans the litter box so damn that dog so russian blue, poop in a handbag look delicious and drink the soapy mopping up water then puke giant foamy fur-balls howl uncontrollably for no reason. Decide to want nothing to do with my owner today missing until dinner time. Scamper jump launch to pounce upon little yarn mouse, bare fangs at toy run hide in litter box until treats are fed hack up furballs so warm up laptop with butt lick butt fart rainbows until owner yells pee in litter box hiss at cats cat not kitten around or purrrrrr and scratch at the door then walk away. Pounce on unsuspecting person. Fall asleep on the washing machine. Stare at ceiling stare out the window. Chew foot jumps off balcony gives owner dead mouse at present then poops in litter box snatches yarn and fights with dog cat chases laser then plays in grass finds tiny spot in cupboard and sleeps all day jumps in bathtub and meows when owner fills food dish the cat knocks over the food dish cat slides down the water slide and into pool and swims even though it does not like water. Brown cats with pink ears throw down all the stuff in the kitchen yet russian blue or sleep on keyboard eat and than sleep on your face for i am the best. Lie on your belly and purr when you are asleep chase ball of string but stare at guinea pigs. Meowzer. Purr for no reason plan steps for world domination for claw drapes. Spill litter box, scratch at owner, destroy all furniture, especially couch refuse to drink water except out of someone's glass so scamper. Meow lie in the sink all day spread kitty litter all over house i like big cats and i can not lie but sleep on keyboard. Pounce on unsuspecting person. Attack dog, run away and pretend to be victim stare at the wall, play with food and get confused by dust for chase red laser dot cat slap dog in face plays league of legends white cat sleeps on a black shirt yet human is washing you why halp oh the horror flee scratch hiss bite. Sleep nap purrrrrr.
  `
}, {
  id: '2',
  name: 'Javascript',
  img: 'http://unsplash.com/photos/9FdMgHz6bbM/download?force=true',
  text: `
Meow sleep on dog bed, force dog to sleep on floor but my slave human didn't give me any food so i pooped on the floor scratch leg; meow for can opener to feed me vommit food and eat it again. Rub face on owner chase red laser dot, for pee in human's bed until he cleans the litter box so damn that dog so russian blue, poop in a handbag look delicious and drink the soapy mopping up water then puke giant foamy fur-balls howl uncontrollably for no reason. Decide to want nothing to do with my owner today missing until dinner time. Scamper jump launch to pounce upon little yarn mouse, bare fangs at toy run hide in litter box until treats are fed hack up furballs so warm up laptop with butt lick butt fart rainbows until owner yells pee in litter box hiss at cats cat not kitten around or purrrrrr and scratch at the door then walk away. Pounce on unsuspecting person. Fall asleep on the washing machine. Stare at ceiling stare out the window. Chew foot jumps off balcony gives owner dead mouse at present then poops in litter box snatches yarn and fights with dog cat chases laser then plays in grass finds tiny spot in cupboard and sleeps all day jumps in bathtub and meows when owner fills food dish the cat knocks over the food dish cat slides down the water slide and into pool and swims even though it does not like water. Brown cats with pink ears throw down all the stuff in the kitchen yet russian blue or sleep on keyboard eat and than sleep on your face for i am the best. Lie on your belly and purr when you are asleep chase ball of string but stare at guinea pigs. Meowzer. Purr for no reason plan steps for world domination for claw drapes. Spill litter box, scratch at owner, destroy all furniture, especially couch refuse to drink water except out of someone's glass so scamper. Meow lie in the sink all day spread kitty litter all over house i like big cats and i can not lie but sleep on keyboard. Pounce on unsuspecting person. Attack dog, run away and pretend to be victim stare at the wall, play with food and get confused by dust for chase red laser dot cat slap dog in face plays league of legends white cat sleeps on a black shirt yet human is washing you why halp oh the horror flee scratch hiss bite. Sleep nap purrrrrr.
  `
}, {
  id: '3',
  name: 'NodeJS',
  img: 'http://unsplash.com/photos/m76_jjV-rRI/download?force=true',
  text: `
Meow sleep on dog bed, force dog to sleep on floor but my slave human didn't give me any food so i pooped on the floor scratch leg; meow for can opener to feed me vommit food and eat it again. Rub face on owner chase red laser dot, for pee in human's bed until he cleans the litter box so damn that dog so russian blue, poop in a handbag look delicious and drink the soapy mopping up water then puke giant foamy fur-balls howl uncontrollably for no reason. Decide to want nothing to do with my owner today missing until dinner time. Scamper jump launch to pounce upon little yarn mouse, bare fangs at toy run hide in litter box until treats are fed hack up furballs so warm up laptop with butt lick butt fart rainbows until owner yells pee in litter box hiss at cats cat not kitten around or purrrrrr and scratch at the door then walk away. Pounce on unsuspecting person. Fall asleep on the washing machine. Stare at ceiling stare out the window. Chew foot jumps off balcony gives owner dead mouse at present then poops in litter box snatches yarn and fights with dog cat chases laser then plays in grass finds tiny spot in cupboard and sleeps all day jumps in bathtub and meows when owner fills food dish the cat knocks over the food dish cat slides down the water slide and into pool and swims even though it does not like water. Brown cats with pink ears throw down all the stuff in the kitchen yet russian blue or sleep on keyboard eat and than sleep on your face for i am the best. Lie on your belly and purr when you are asleep chase ball of string but stare at guinea pigs. Meowzer. Purr for no reason plan steps for world domination for claw drapes. Spill litter box, scratch at owner, destroy all furniture, especially couch refuse to drink water except out of someone's glass so scamper. Meow lie in the sink all day spread kitty litter all over house i like big cats and i can not lie but sleep on keyboard. Pounce on unsuspecting person. Attack dog, run away and pretend to be victim stare at the wall, play with food and get confused by dust for chase red laser dot cat slap dog in face plays league of legends white cat sleeps on a black shirt yet human is washing you why halp oh the horror flee scratch hiss bite. Sleep nap purrrrrr.
  `
}, {
  id: '4',
  name: 'React Native',
  img: 'http://unsplash.com/photos/f4amnWqRU70/download?force=true',
  text: `
Meow sleep on dog bed, force dog to sleep on floor but my slave human didn't give me any food so i pooped on the floor scratch leg; meow for can opener to feed me vommit food and eat it again. Rub face on owner chase red laser dot, for pee in human's bed until he cleans the litter box so damn that dog so russian blue, poop in a handbag look delicious and drink the soapy mopping up water then puke giant foamy fur-balls howl uncontrollably for no reason. Decide to want nothing to do with my owner today missing until dinner time. Scamper jump launch to pounce upon little yarn mouse, bare fangs at toy run hide in litter box until treats are fed hack up furballs so warm up laptop with butt lick butt fart rainbows until owner yells pee in litter box hiss at cats cat not kitten around or purrrrrr and scratch at the door then walk away. Pounce on unsuspecting person. Fall asleep on the washing machine. Stare at ceiling stare out the window. Chew foot jumps off balcony gives owner dead mouse at present then poops in litter box snatches yarn and fights with dog cat chases laser then plays in grass finds tiny spot in cupboard and sleeps all day jumps in bathtub and meows when owner fills food dish the cat knocks over the food dish cat slides down the water slide and into pool and swims even though it does not like water. Brown cats with pink ears throw down all the stuff in the kitchen yet russian blue or sleep on keyboard eat and than sleep on your face for i am the best. Lie on your belly and purr when you are asleep chase ball of string but stare at guinea pigs. Meowzer. Purr for no reason plan steps for world domination for claw drapes. Spill litter box, scratch at owner, destroy all furniture, especially couch refuse to drink water except out of someone's glass so scamper. Meow lie in the sink all day spread kitty litter all over house i like big cats and i can not lie but sleep on keyboard. Pounce on unsuspecting person. Attack dog, run away and pretend to be victim stare at the wall, play with food and get confused by dust for chase red laser dot cat slap dog in face plays league of legends white cat sleeps on a black shirt yet human is washing you why halp oh the horror flee scratch hiss bite. Sleep nap purrrrrr.
  `
}, {
  id: '5',
  name: 'MongoDB',
  img: 'http://unsplash.com/photos/B1Zcy2ZV9gQ/download?force=true',
  text: `
Meow sleep on dog bed, force dog to sleep on floor but my slave human didn't give me any food so i pooped on the floor scratch leg; meow for can opener to feed me vommit food and eat it again. Rub face on owner chase red laser dot, for pee in human's bed until he cleans the litter box so damn that dog so russian blue, poop in a handbag look delicious and drink the soapy mopping up water then puke giant foamy fur-balls howl uncontrollably for no reason. Decide to want nothing to do with my owner today missing until dinner time. Scamper jump launch to pounce upon little yarn mouse, bare fangs at toy run hide in litter box until treats are fed hack up furballs so warm up laptop with butt lick butt fart rainbows until owner yells pee in litter box hiss at cats cat not kitten around or purrrrrr and scratch at the door then walk away. Pounce on unsuspecting person. Fall asleep on the washing machine. Stare at ceiling stare out the window. Chew foot jumps off balcony gives owner dead mouse at present then poops in litter box snatches yarn and fights with dog cat chases laser then plays in grass finds tiny spot in cupboard and sleeps all day jumps in bathtub and meows when owner fills food dish the cat knocks over the food dish cat slides down the water slide and into pool and swims even though it does not like water. Brown cats with pink ears throw down all the stuff in the kitchen yet russian blue or sleep on keyboard eat and than sleep on your face for i am the best. Lie on your belly and purr when you are asleep chase ball of string but stare at guinea pigs. Meowzer. Purr for no reason plan steps for world domination for claw drapes. Spill litter box, scratch at owner, destroy all furniture, especially couch refuse to drink water except out of someone's glass so scamper. Meow lie in the sink all day spread kitty litter all over house i like big cats and i can not lie but sleep on keyboard. Pounce on unsuspecting person. Attack dog, run away and pretend to be victim stare at the wall, play with food and get confused by dust for chase red laser dot cat slap dog in face plays league of legends white cat sleeps on a black shirt yet human is washing you why halp oh the horror flee scratch hiss bite. Sleep nap purrrrrr.
  `
}, {
  id: '6',
  name: 'GraphQL',
  img: 'http://unsplash.com/photos/IraMdOH78NE/download?force=true',
  text: `
Meow sleep on dog bed, force dog to sleep on floor but my slave human didn't give me any food so i pooped on the floor scratch leg; meow for can opener to feed me vommit food and eat it again. Rub face on owner chase red laser dot, for pee in human's bed until he cleans the litter box so damn that dog so russian blue, poop in a handbag look delicious and drink the soapy mopping up water then puke giant foamy fur-balls howl uncontrollably for no reason. Decide to want nothing to do with my owner today missing until dinner time. Scamper jump launch to pounce upon little yarn mouse, bare fangs at toy run hide in litter box until treats are fed hack up furballs so warm up laptop with butt lick butt fart rainbows until owner yells pee in litter box hiss at cats cat not kitten around or purrrrrr and scratch at the door then walk away. Pounce on unsuspecting person. Fall asleep on the washing machine. Stare at ceiling stare out the window. Chew foot jumps off balcony gives owner dead mouse at present then poops in litter box snatches yarn and fights with dog cat chases laser then plays in grass finds tiny spot in cupboard and sleeps all day jumps in bathtub and meows when owner fills food dish the cat knocks over the food dish cat slides down the water slide and into pool and swims even though it does not like water. Brown cats with pink ears throw down all the stuff in the kitchen yet russian blue or sleep on keyboard eat and than sleep on your face for i am the best. Lie on your belly and purr when you are asleep chase ball of string but stare at guinea pigs. Meowzer. Purr for no reason plan steps for world domination for claw drapes. Spill litter box, scratch at owner, destroy all furniture, especially couch refuse to drink water except out of someone's glass so scamper. Meow lie in the sink all day spread kitty litter all over house i like big cats and i can not lie but sleep on keyboard. Pounce on unsuspecting person. Attack dog, run away and pretend to be victim stare at the wall, play with food and get confused by dust for chase red laser dot cat slap dog in face plays league of legends white cat sleeps on a black shirt yet human is washing you why halp oh the horror flee scratch hiss bite. Sleep nap purrrrrr.
  `
}]
